// The standard environment for expr-lang.

use super::id_table::{DeclOrId, IdentificationTable};
use crate::front::ast::*;
use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    pub static ref STDENV: HashMap<&'static str, Decl> = {
        let mut m = HashMap::new();
        m.insert("false", Decl::ConstDecl(ConstDecl::BoolLiteral(false)));
        m.insert("true", Decl::ConstDecl(ConstDecl::BoolLiteral(true)));
        m.insert(
            "unary_plus",
            Decl::OperatorDecl(OperatorDecl::UnaryOperatorDecl(UnaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "unary_minus",
            Decl::OperatorDecl(OperatorDecl::UnaryOperatorDecl(UnaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "bitwise_not",
            Decl::OperatorDecl(OperatorDecl::UnaryOperatorDecl(UnaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
            ))),
        );

        m.insert(
            "logical_not",
            Decl::OperatorDecl(OperatorDecl::UnaryOperatorDecl(UnaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
            ))),
        );

        m.insert(
            "add",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "add_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::AnyType,
                Type::AnyType,
                Type::AnyType,
            ))),
        );

        m.insert(
            "bitwise_and",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "bitwise_and_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "bitwise_or",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "bitwise_or_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m.insert(
            "bitwise_xor",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "bitwise_xor_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "div",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "div_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "equal",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::AnyType,
                Type::AnyType,
                Type::AnyType,
            ))),
        );
        m.insert(
            "greater_than",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "greater_than_or_equal",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "left_shift",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "left_shift_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "less_than",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "less_than_or_equal",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "logical_and",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
                Type::BoolType,
            ))),
        );
        m.insert(
            "logical_and_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
                Type::BoolType,
            ))),
        );
        m.insert(
            "logical_or",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
                Type::BoolType,
            ))),
        );
        m.insert(
            "logical_or_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::BoolType,
                Type::BoolType,
                Type::BoolType,
            ))),
        );
        m.insert(
            "mod",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "mod_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "mul",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "mul_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "not_equal",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::AnyType,
                Type::AnyType,
                Type::AnyType,
            ))),
        );
        m.insert(
            "right_shift",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "right_shift_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "sub",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );
        m.insert(
            "sub_assign",
            Decl::OperatorDecl(OperatorDecl::BinaryOperatorDecl(BinaryOperatorDecl::new(
                Type::IntType,
                Type::IntType,
                Type::IntType,
            ))),
        );

        m
    };
}

/// Loads the standard environment at level 0.
pub fn load_stdenv(id_table: &mut IdentificationTable) {
    id_table.save_attr(
        "bitwise_not",
        DeclOrId::Decl(STDENV.get("bitwise_not").unwrap().clone()),
    );
    id_table.save_attr(
        "logical_not",
        DeclOrId::Decl(STDENV.get("logical_not").unwrap().clone()),
    );

    id_table.save_attr(
        "unary_plus",
        DeclOrId::Decl(STDENV.get("unary_plus").unwrap().clone()),
    );

    id_table.save_attr(
        "unary_minus",
        DeclOrId::Decl(STDENV.get("unary_minus").unwrap().clone()),
    );

    id_table.save_attr(
        "assign",
        DeclOrId::Decl(STDENV.get("assign").unwrap().clone()),
    );

    id_table.save_attr("add", DeclOrId::Decl(STDENV.get("add").unwrap().clone()));
    id_table.save_attr(
        "add_assign",
        DeclOrId::Decl(STDENV.get("add_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "bitwise_and",
        DeclOrId::Decl(STDENV.get("bitwise_and").unwrap().clone()),
    );

    id_table.save_attr(
        "bitwise_and_assign",
        DeclOrId::Decl(STDENV.get("bitwise_and_assign").unwrap().clone()),
    );

    id_table.save_attr(
        "bitwise_or",
        DeclOrId::Decl(STDENV.get("bitwise_or").unwrap().clone()),
    );
    id_table.save_attr(
        "bitwise_or_assign",
        DeclOrId::Decl(STDENV.get("bitwise_or_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "bitwise_xor",
        DeclOrId::Decl(STDENV.get("bitwise_xor").unwrap().clone()),
    );
    id_table.save_attr(
        "bitwise_xor_assign",
        DeclOrId::Decl(STDENV.get("bitwise_xor_assign").unwrap().clone()),
    );
    id_table.save_attr("div", DeclOrId::Decl(STDENV.get("div").unwrap().clone()));
    id_table.save_attr(
        "div_assign",
        DeclOrId::Decl(STDENV.get("div_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "equal",
        DeclOrId::Decl(STDENV.get("equal").unwrap().clone()),
    );
    id_table.save_attr(
        "greater_than",
        DeclOrId::Decl(STDENV.get("greater_than").unwrap().clone()),
    );
    id_table.save_attr(
        "greater_than_or_equal",
        DeclOrId::Decl(STDENV.get("greater_than_or_equal").unwrap().clone()),
    );
    id_table.save_attr(
        "left_shift",
        DeclOrId::Decl(STDENV.get("left_shift").unwrap().clone()),
    );
    id_table.save_attr(
        "left_shift_assign",
        DeclOrId::Decl(STDENV.get("left_shift_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "less_than",
        DeclOrId::Decl(STDENV.get("less_than").unwrap().clone()),
    );
    id_table.save_attr(
        "less_than_or_equal",
        DeclOrId::Decl(STDENV.get("less_than_or_equal").unwrap().clone()),
    );
    id_table.save_attr(
        "logical_and",
        DeclOrId::Decl(STDENV.get("logical_and").unwrap().clone()),
    );
    id_table.save_attr(
        "logical_and_assign",
        DeclOrId::Decl(STDENV.get("logical_and_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "logical_or",
        DeclOrId::Decl(STDENV.get("logical_or").unwrap().clone()),
    );
    id_table.save_attr(
        "logical_or_assign",
        DeclOrId::Decl(STDENV.get("logical_or_assign").unwrap().clone()),
    );
    id_table.save_attr("mod", DeclOrId::Decl(STDENV.get("mod").unwrap().clone()));
    id_table.save_attr(
        "mod_assign",
        DeclOrId::Decl(STDENV.get("mod_assign").unwrap().clone()),
    );
    id_table.save_attr("mul", DeclOrId::Decl(STDENV.get("mul").unwrap().clone()));
    id_table.save_attr(
        "mul_assign",
        DeclOrId::Decl(STDENV.get("mul_assign").unwrap().clone()),
    );
    id_table.save_attr(
        "not_equal",
        DeclOrId::Decl(STDENV.get("not_equal").unwrap().clone()),
    );
    id_table.save_attr(
        "right_shift",
        DeclOrId::Decl(STDENV.get("right_shift").unwrap().clone()),
    );
    id_table.save_attr(
        "right_shift_assign",
        DeclOrId::Decl(STDENV.get("right_shift_assign").unwrap().clone()),
    );
    id_table.save_attr("sub", DeclOrId::Decl(STDENV.get("sub").unwrap().clone()));
    id_table.save_attr(
        "sub_assign",
        DeclOrId::Decl(STDENV.get("sub_assign").unwrap().clone().clone()),
    );
}
